package com.company.project.model;

import java.util.Date;

public class Cnc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc.cnc_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    private String cncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc.company_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc.line_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    private String lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc.cnc_number
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    private String cncNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc.cnc_code
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    private String cncCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc.create_time
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc.cnc_id
     *
     * @return the value of cnc.cnc_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public String getCncId() {
        return cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc.cnc_id
     *
     * @param cncId the value for cnc.cnc_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public void setCncId(String cncId) {
        this.cncId = cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc.company_id
     *
     * @return the value of cnc.company_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc.company_id
     *
     * @param companyId the value for cnc.company_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc.line_id
     *
     * @return the value of cnc.line_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc.line_id
     *
     * @param lineId the value for cnc.line_id
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc.cnc_number
     *
     * @return the value of cnc.cnc_number
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public String getCncNumber() {
        return cncNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc.cnc_number
     *
     * @param cncNumber the value for cnc.cnc_number
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public void setCncNumber(String cncNumber) {
        this.cncNumber = cncNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc.cnc_code
     *
     * @return the value of cnc.cnc_code
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public String getCncCode() {
        return cncCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc.cnc_code
     *
     * @param cncCode the value for cnc.cnc_code
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public void setCncCode(String cncCode) {
        this.cncCode = cncCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc.create_time
     *
     * @return the value of cnc.create_time
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc.create_time
     *
     * @param createTime the value for cnc.create_time
     *
     * @mbg.generated Thu May 14 18:48:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}