package com.company.project.model;

import java.util.Date;

public class CncFixture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_fixture.fixture_id
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    private String fixtureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_fixture.cnc_id
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    private String cncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_fixture.fixture_name
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    private String fixtureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_fixture.fixture_code
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    private String fixtureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_fixture.rfid
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    private String rfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_fixture.create_time
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_fixture.fixture_id
     *
     * @return the value of cnc_fixture.fixture_id
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public String getFixtureId() {
        return fixtureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_fixture.fixture_id
     *
     * @param fixtureId the value for cnc_fixture.fixture_id
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public void setFixtureId(String fixtureId) {
        this.fixtureId = fixtureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_fixture.cnc_id
     *
     * @return the value of cnc_fixture.cnc_id
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public String getCncId() {
        return cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_fixture.cnc_id
     *
     * @param cncId the value for cnc_fixture.cnc_id
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public void setCncId(String cncId) {
        this.cncId = cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_fixture.fixture_name
     *
     * @return the value of cnc_fixture.fixture_name
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public String getFixtureName() {
        return fixtureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_fixture.fixture_name
     *
     * @param fixtureName the value for cnc_fixture.fixture_name
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public void setFixtureName(String fixtureName) {
        this.fixtureName = fixtureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_fixture.fixture_code
     *
     * @return the value of cnc_fixture.fixture_code
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public String getFixtureCode() {
        return fixtureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_fixture.fixture_code
     *
     * @param fixtureCode the value for cnc_fixture.fixture_code
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public void setFixtureCode(String fixtureCode) {
        this.fixtureCode = fixtureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_fixture.rfid
     *
     * @return the value of cnc_fixture.rfid
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public String getRfid() {
        return rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_fixture.rfid
     *
     * @param rfid the value for cnc_fixture.rfid
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_fixture.create_time
     *
     * @return the value of cnc_fixture.create_time
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_fixture.create_time
     *
     * @param createTime the value for cnc_fixture.create_time
     *
     * @mbg.generated Fri May 15 11:41:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}