package com.company.project.model;

import java.util.Date;

public class CncHilt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_hilt.hilt_id
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    private String hiltId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_hilt.cnc_id
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    private String cncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_hilt.hilt_name
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    private String hiltName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_hilt.hilt_code
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    private String hiltCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_hilt.rfid
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    private String rfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_hilt.create_time
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_hilt.hilt_id
     *
     * @return the value of cnc_hilt.hilt_id
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public String getHiltId() {
        return hiltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_hilt.hilt_id
     *
     * @param hiltId the value for cnc_hilt.hilt_id
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public void setHiltId(String hiltId) {
        this.hiltId = hiltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_hilt.cnc_id
     *
     * @return the value of cnc_hilt.cnc_id
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public String getCncId() {
        return cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_hilt.cnc_id
     *
     * @param cncId the value for cnc_hilt.cnc_id
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public void setCncId(String cncId) {
        this.cncId = cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_hilt.hilt_name
     *
     * @return the value of cnc_hilt.hilt_name
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public String getHiltName() {
        return hiltName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_hilt.hilt_name
     *
     * @param hiltName the value for cnc_hilt.hilt_name
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public void setHiltName(String hiltName) {
        this.hiltName = hiltName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_hilt.hilt_code
     *
     * @return the value of cnc_hilt.hilt_code
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public String getHiltCode() {
        return hiltCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_hilt.hilt_code
     *
     * @param hiltCode the value for cnc_hilt.hilt_code
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public void setHiltCode(String hiltCode) {
        this.hiltCode = hiltCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_hilt.rfid
     *
     * @return the value of cnc_hilt.rfid
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public String getRfid() {
        return rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_hilt.rfid
     *
     * @param rfid the value for cnc_hilt.rfid
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_hilt.create_time
     *
     * @return the value of cnc_hilt.create_time
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_hilt.create_time
     *
     * @param createTime the value for cnc_hilt.create_time
     *
     * @mbg.generated Fri May 15 12:04:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}