package com.company.project.model;

import java.util.Date;

public class CncProgram {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_program.program_id
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    private String programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_program.cnc_id
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    private String cncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_program.program_name
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    private String programName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_program.create_time
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_program.program_id
     *
     * @return the value of cnc_program.program_id
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_program.program_id
     *
     * @param programId the value for cnc_program.program_id
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public void setProgramId(String programId) {
        this.programId = programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_program.cnc_id
     *
     * @return the value of cnc_program.cnc_id
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public String getCncId() {
        return cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_program.cnc_id
     *
     * @param cncId the value for cnc_program.cnc_id
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public void setCncId(String cncId) {
        this.cncId = cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_program.program_name
     *
     * @return the value of cnc_program.program_name
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_program.program_name
     *
     * @param programName the value for cnc_program.program_name
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public void setProgramName(String programName) {
        this.programName = programName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_program.create_time
     *
     * @return the value of cnc_program.create_time
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_program.create_time
     *
     * @param createTime the value for cnc_program.create_time
     *
     * @mbg.generated Fri May 15 12:15:03 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}