package com.company.project.model;

import java.util.Date;

public class CncProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_product.product_id
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_product.cnc_id
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    private String cncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_product.product_name
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_product.product_code
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_product.rfid
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    private String rfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_product.create_time
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_product.product_id
     *
     * @return the value of cnc_product.product_id
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_product.product_id
     *
     * @param productId the value for cnc_product.product_id
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_product.cnc_id
     *
     * @return the value of cnc_product.cnc_id
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public String getCncId() {
        return cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_product.cnc_id
     *
     * @param cncId the value for cnc_product.cnc_id
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public void setCncId(String cncId) {
        this.cncId = cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_product.product_name
     *
     * @return the value of cnc_product.product_name
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_product.product_name
     *
     * @param productName the value for cnc_product.product_name
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_product.product_code
     *
     * @return the value of cnc_product.product_code
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_product.product_code
     *
     * @param productCode the value for cnc_product.product_code
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_product.rfid
     *
     * @return the value of cnc_product.rfid
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public String getRfid() {
        return rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_product.rfid
     *
     * @param rfid the value for cnc_product.rfid
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_product.create_time
     *
     * @return the value of cnc_product.create_time
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_product.create_time
     *
     * @param createTime the value for cnc_product.create_time
     *
     * @mbg.generated Fri May 15 12:13:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}