package com.company.project.model;

import java.util.Date;

public class CncTool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_tool.tool_id
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    private String toolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_tool.cnc_id
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    private String cncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_tool.tool_name
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    private String toolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_tool.tool_code
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    private String toolCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_tool.rfid
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    private String rfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnc_tool.create_time
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_tool.tool_id
     *
     * @return the value of cnc_tool.tool_id
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public String getToolId() {
        return toolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_tool.tool_id
     *
     * @param toolId the value for cnc_tool.tool_id
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public void setToolId(String toolId) {
        this.toolId = toolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_tool.cnc_id
     *
     * @return the value of cnc_tool.cnc_id
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public String getCncId() {
        return cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_tool.cnc_id
     *
     * @param cncId the value for cnc_tool.cnc_id
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public void setCncId(String cncId) {
        this.cncId = cncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_tool.tool_name
     *
     * @return the value of cnc_tool.tool_name
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public String getToolName() {
        return toolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_tool.tool_name
     *
     * @param toolName the value for cnc_tool.tool_name
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public void setToolName(String toolName) {
        this.toolName = toolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_tool.tool_code
     *
     * @return the value of cnc_tool.tool_code
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public String getToolCode() {
        return toolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_tool.tool_code
     *
     * @param toolCode the value for cnc_tool.tool_code
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public void setToolCode(String toolCode) {
        this.toolCode = toolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_tool.rfid
     *
     * @return the value of cnc_tool.rfid
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public String getRfid() {
        return rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_tool.rfid
     *
     * @param rfid the value for cnc_tool.rfid
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnc_tool.create_time
     *
     * @return the value of cnc_tool.create_time
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnc_tool.create_time
     *
     * @param createTime the value for cnc_tool.create_time
     *
     * @mbg.generated Fri May 15 12:16:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}