package com.company.project.model;

import java.util.Date;

public class TbCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.company_id
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.company_name
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.create_time
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.company_id
     *
     * @return the value of tb_company.company_id
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.company_id
     *
     * @param companyId the value for tb_company.company_id
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.company_name
     *
     * @return the value of tb_company.company_name
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.company_name
     *
     * @param companyName the value for tb_company.company_name
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.create_time
     *
     * @return the value of tb_company.create_time
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.create_time
     *
     * @param createTime the value for tb_company.create_time
     *
     * @mbg.generated Fri May 15 12:18:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}